logsBucket: gs://gcloud-jho-cloudbuild-logs

steps:
  # 0) Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/gcloud-jho/gke-vision-repo/vision-go-demo',
        '.',
      ]

  # 1) Artifact Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/gcloud-jho/gke-vision-repo/vision-go-demo',
      ]

  # 2) deployment.yaml 적용
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=vision-cluster'
    args: ['apply', '-f', 'deployment.yaml']

  # 3) 롤링 업데이트 트리거
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=vision-cluster'
    args: ['rollout', 'restart', 'deployment/vision-go-app']