logsBucket: gs://gcloud-jho-cloudbuild-logs
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/gcloud-jho/vision-repo/vision-go-demo', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/gcloud-jho/vision-repo/vision-go-demo']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=vision-cluster'